POST http://localhost:3001/api/blogs

Content-Type: application/json

authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoZWNrd2Rxd2QiLCJpZCI6IjYyOTIyN2JjOWVmYzg4NzU2MDZlODFmNiIsImlhdCI6MTY1Mzc0NjQ1MiwiZXhwIjoxNjUzNzUwMDUyfQ.CwcnWQMWOlEL2H5u9d6LXXCs8NnN6lDuu-72LtT_c7Q
{
    "title": "tulikotää",
    "author": "houppiffff",
    "url": "www.nouppi.fi"

}